"""create source_revisions

Revision ID: 2e060706eb51
Revises: 06ae6e5ff8b9
Create Date: 2026-05-08 19:20:42.874174

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2e060706eb51"
down_revision: str | Sequence[str] | None = "06ae6e5ff8b9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "source_revisions",
        sa.Column("source_revision_id", sa.String(length=26), nullable=False),
        sa.Column("info_source_id", sa.String(length=26), nullable=False),
        sa.Column("content_fingerprint", sa.Text(), nullable=False),
        sa.Column("captured_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("content_size_bytes", sa.BigInteger(), nullable=True),
        sa.Column("content_media_type", sa.Text(), nullable=True),
        sa.Column("content_cache_uri", sa.Text(), nullable=True),
        sa.Column("content_cache_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["info_source_id"], ["information.info_sources.info_source_id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("source_revision_id"),
        sa.UniqueConstraint(
            "info_source_id", "content_fingerprint", name="uq_source_revisions_source_fingerprint"
        ),
        schema="information",
    )
    op.create_index(
        "ix_source_revisions_source_captured",
        "source_revisions",
        ["info_source_id", "captured_at"],
        unique=False,
        schema="information",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_source_revisions_source_captured", table_name="source_revisions", schema="information"
    )
    op.drop_table("source_revisions", schema="information")
    # ### end Alembic commands ###
