"""create replication_commands

The issuer's durable record of one ``content.replicate`` occasion (archiver#169,
step 5 of the #137 epic). Written in the same transaction as the revision insert
and the outbox row, which is what makes "revision recorded" and "replication
requested" inseparable.

Three readers justify a table rather than a log line: MUST-2's
``command_id → (assignment, revision)`` mapping, which has to be durable before
the XADD; MUST-6's reaper, since Replicator does not guarantee that every command
either succeeds or is closed; and the dashboard (archiver#171), where a *skipped*
replication that leaves no row reads as "not yet" forever.

``command_id`` is Text, not a ULID column, though issuance mints ULIDs: it is a
wire value Replicator echoes back verbatim, and the consumer must be able to look
up whatever string arrives without a parse that can fail.

New table, no backfill — the registry has issued no replication before this.
``downgrade()`` drops it, losing the issuance history; nothing else holds it, and
before this revision nothing did.

Revision ID: 39f21d31fdec
Revises: b3f61a20d7c4
Create Date: 2026-08-17

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "39f21d31fdec"
down_revision: str | Sequence[str] | None = "b3f61a20d7c4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "replication_commands",
        sa.Column("command_id", sa.Text(), nullable=False),
        sa.Column("info_item_rep_spec_id", sa.String(length=26), nullable=False),
        sa.Column("source_revision_id", sa.String(length=26), nullable=False),
        sa.Column("info_source_id", sa.String(length=26), nullable=False),
        sa.Column("provider", sa.String(length=50), nullable=False),
        sa.Column("credentials_alias", sa.Text(), nullable=False),
        sa.Column("destination", sa.Text(), nullable=True),
        sa.Column("media_type", sa.Text(), nullable=False),
        sa.Column("blob_uri", sa.Text(), nullable=True),
        sa.Column("object_options", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "issued_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("state", sa.String(length=20), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("detail", sa.Text(), nullable=True),
        sa.Column("terminal", sa.Boolean(), nullable=True),
        sa.Column("attempts", sa.Integer(), nullable=True),
        sa.Column("public_url", sa.Text(), nullable=True),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["info_item_rep_spec_id"], ["information.info_item_rep_specs.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["info_source_id"], ["information.info_sources.info_source_id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["source_revision_id"],
            ["information.source_revisions.source_revision_id"],
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("command_id"),
        schema="information",
    )
    op.create_index(
        "ix_replication_commands_open",
        "replication_commands",
        ["issued_at"],
        unique=False,
        schema="information",
        postgresql_where=sa.text("closed_at IS NULL AND state = 'requested'"),
    )
    op.create_index(
        "ix_replication_commands_revision",
        "replication_commands",
        ["source_revision_id"],
        unique=False,
        schema="information",
    )
    op.create_index(
        "ix_replication_commands_target",
        "replication_commands",
        ["info_item_rep_spec_id", "issued_at"],
        unique=False,
        schema="information",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_replication_commands_target", table_name="replication_commands", schema="information"
    )
    op.drop_index(
        "ix_replication_commands_revision", table_name="replication_commands", schema="information"
    )
    op.drop_index(
        "ix_replication_commands_open",
        table_name="replication_commands",
        schema="information",
        postgresql_where=sa.text("closed_at IS NULL AND state = 'requested'"),
    )
    op.drop_table("replication_commands", schema="information")
    # ### end Alembic commands ###
