"""add ix_rep_specs_created_at_id for list pagination

Revision ID: 9cdd4b999882
Revises: d252ea2815af
Create Date: 2026-05-11 23:40:03.171688

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9cdd4b999882"
down_revision: str | Sequence[str] | None = "d252ea2815af"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_rep_specs_created_at_id",
        "rep_specs",
        ["created_at", "rep_spec_id"],
        unique=False,
        schema="information",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_rep_specs_created_at_id", table_name="rep_specs", schema="information")
    # ### end Alembic commands ###
