"""create changes_outbox

Revision ID: a12c1624655c
Revises: 0ba89c365552
Create Date: 2026-05-08 22:50:10.776287

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "a12c1624655c"
down_revision: str | Sequence[str] | None = "0ba89c365552"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "changes_outbox",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("topic", sa.String(length=64), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("bus_message_id", sa.String(length=64), nullable=True),
        sa.Column("publish_attempts", sa.Integer(), server_default="0", nullable=False),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        schema="information",
    )
    op.create_index(
        "ix_changes_outbox_unpublished_created",
        "changes_outbox",
        ["created_at"],
        unique=False,
        schema="information",
        postgresql_where=sa.text("published_at IS NULL"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_changes_outbox_unpublished_created",
        table_name="changes_outbox",
        schema="information",
        postgresql_where=sa.text("published_at IS NULL"),
    )
    op.drop_table("changes_outbox", schema="information")
    # ### end Alembic commands ###
