"""create info_item_sources

Revision ID: d86c8caac3d4
Revises: 2e060706eb51
Create Date: 2026-05-08 19:26:54.332146

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d86c8caac3d4"
down_revision: str | Sequence[str] | None = "2e060706eb51"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "info_item_sources",
        sa.Column("info_item_id", sa.String(length=26), nullable=False),
        sa.Column("info_source_id", sa.String(length=26), nullable=False),
        sa.Column("role", sa.String(length=50), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deactivated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["info_item_id"],
            ["information.info_items.info_item_id"],
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["info_source_id"],
            ["information.info_sources.info_source_id"],
        ),
        sa.PrimaryKeyConstraint("info_item_id", "info_source_id"),
        schema="information",
    )
    op.create_index(
        "uq_info_item_sources_active_primary",
        "info_item_sources",
        ["info_item_id"],
        unique=True,
        schema="information",
        postgresql_where=sa.text("deactivated_at IS NULL AND role = 'primary'"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_info_item_sources_active_primary",
        table_name="info_item_sources",
        schema="information",
        postgresql_where=sa.text("deactivated_at IS NULL AND role = 'primary'"),
    )
    op.drop_table("info_item_sources", schema="information")
    # ### end Alembic commands ###
