"""create persist_commands; source_revisions blob_fingerprint and persisted_at

The return leg of ``content.persist`` (archiver#276, replicator#114): Replicator
copies a revision's raw bytes into its content-addressed permanent store, and the
outcome lands here. The issuer side comes later, when broker#64 grants the XADD
and Replicator's persist handler ships; this revision lets the
``content.artifacts`` consumer apply outcomes as soon as co-core >= 0.19.6 decodes
them, rather than acking them as foreign events.

``persist_commands`` mirrors ``replication_commands``: MUST-2's durable
``command_id`` mapping, the open-command index, the state vocabulary enforced in
the database. It is the only link from an outcome back to the registry, because
the persist facts carry no domain echo.

``source_revisions.blob_fingerprint`` is the raw-bytes digest (not the extracted
``content_fingerprint``) and the permanent store's address; ``persisted_at`` is the
minimum ``occurred_at`` over every success fact for it. Both nullable, no
backfill: existing rows never received a digest, and deriving one from a
``content_cache_uri`` path is what the replicate contract's T3a forbids.
``downgrade()`` drops the table and both columns, losing persist history.

Revision ID: e964909e0c62
Revises: c9f4a1b7d503
Create Date: 2026-09-25 22:56:33.420354

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e964909e0c62"
down_revision: str | Sequence[str] | None = "c9f4a1b7d503"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "persist_commands",
        sa.Column("command_id", sa.Text(), nullable=False),
        sa.Column("source_revision_id", sa.String(length=26), nullable=False),
        sa.Column("content_fingerprint", sa.Text(), nullable=False),
        sa.Column("blob_uri", sa.Text(), nullable=False),
        sa.Column("media_type", sa.Text(), nullable=False),
        sa.Column(
            "issued_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("state", sa.String(length=20), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("detail", sa.Text(), nullable=True),
        sa.Column("terminal", sa.Boolean(), nullable=True),
        sa.Column("size_bytes", sa.BigInteger(), nullable=True),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_fact_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "state IN ('requested', 'persisted', 'failed', 'abandoned')",
            name="ck_persist_commands_state",
        ),
        sa.ForeignKeyConstraint(
            ["source_revision_id"],
            ["information.source_revisions.source_revision_id"],
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("command_id"),
        schema="information",
    )
    op.create_index(
        "ix_persist_commands_fingerprint",
        "persist_commands",
        ["content_fingerprint"],
        unique=False,
        schema="information",
    )
    op.create_index(
        "ix_persist_commands_open",
        "persist_commands",
        ["issued_at"],
        unique=False,
        schema="information",
        postgresql_where=sa.text("closed_at IS NULL AND state = 'requested'"),
    )
    op.create_index(
        "ix_persist_commands_revision",
        "persist_commands",
        ["source_revision_id"],
        unique=False,
        schema="information",
    )
    op.add_column(
        "source_revisions",
        sa.Column("blob_fingerprint", sa.Text(), nullable=True),
        schema="information",
    )
    op.add_column(
        "source_revisions",
        sa.Column("persisted_at", sa.DateTime(timezone=True), nullable=True),
        schema="information",
    )
    op.create_index(
        "ix_source_revisions_blob_fingerprint",
        "source_revisions",
        ["blob_fingerprint"],
        unique=False,
        schema="information",
        postgresql_where=sa.text("blob_fingerprint IS NOT NULL"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_source_revisions_blob_fingerprint",
        table_name="source_revisions",
        schema="information",
        postgresql_where=sa.text("blob_fingerprint IS NOT NULL"),
    )
    op.drop_column("source_revisions", "persisted_at", schema="information")
    op.drop_column("source_revisions", "blob_fingerprint", schema="information")
    op.drop_index(
        "ix_persist_commands_revision", table_name="persist_commands", schema="information"
    )
    op.drop_index(
        "ix_persist_commands_open",
        table_name="persist_commands",
        schema="information",
        postgresql_where=sa.text("closed_at IS NULL AND state = 'requested'"),
    )
    op.drop_index(
        "ix_persist_commands_fingerprint", table_name="persist_commands", schema="information"
    )
    op.drop_table("persist_commands", schema="information")
    # ### end Alembic commands ###
