"""announcement generation + revoked_info_items

Revision ID: f5c522f65657
Revises: b41d7c9e05a2
Create Date: 2026-08-13 15:14:29.031365

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f5c522f65657"
down_revision: str | Sequence[str] | None = "b41d7c9e05a2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "revoked_info_items",
        sa.Column("info_item_id", sa.String(length=26), nullable=False),
        sa.Column("generation", sa.BigInteger(), nullable=False),
        sa.Column(
            "revoked_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("info_item_id"),
        schema="information",
    )
    op.add_column(
        "info_items",
        sa.Column("announcement_generation", sa.BigInteger(), server_default="0", nullable=False),
        schema="information",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("info_items", "announcement_generation", schema="information")
    op.drop_table("revoked_info_items", schema="information")
    # ### end Alembic commands ###
