"""The cadence workflow resolves each script, and records each number it sweeps.

``.github/workflows/context-cadence.yml`` is generated by curating-context's
``install-cadence.sh`` and runs five of that skill's scripts. Its resolve step
used to probe a single anchor - ``measure-context.sh`` - and export the
*directory* it was found in, which every later step then joined a script name
onto. A project ``scripts/`` holding that one file sent the others to a
directory that lacks them (gregoryfoster/skills#301, fixed upstream in
``7b0ef6a`` and carried here by archiver#243).

Latent rather than live: archiver's ``scripts/`` holds ``dev_server.sh`` and
``sync_wheelhouse.py``, none of the cadence scripts. But it is a scheduled job
with a credential and a push, so its failure mode is a red Monday-morning run
nobody is watching, and the cheapest guard is to execute the step.

**Runs the workflow's own shell rather than asserting on its text.** A regex
over YAML would pass on a step that exports the right names and resolves them
wrongly. The step is extracted verbatim and run under ``bash -e`` against
fixture projects, which is what upstream's ``test_per_script_resolution.py``
does for the three copies it pins to each other.

The same treatment covers the sweep step's four telemetry variables
(archiver#249). Their failure is quieter than a missing script and was live for
37 of 42 rows: a sweep that never ran, or a variable the record step never
forwards, writes ``null`` into the ledger field and the job stays green. So the
exports are paired with the flags that consume them, and the step is run with
stub check scripts to prove each number survives the round trip.
"""

import re
import subprocess
import tempfile
from functools import cache
from pathlib import Path

import pytest

from tests.scripts._skills_lists import REPO_ROOT

WORKFLOW = REPO_ROOT / ".github" / "workflows" / "context-cadence.yml"
RESOLVE_STEP = "Resolve the skill scripts"
SWEEP_STEP = "Sweep the seams and the counts"
RECORD_STEP = "Measure and record"

# The scripts this workflow actually runs - five since archiver#249 took the
# counts sweep (gregoryfoster/skills#258). A resolve step is entitled to fail on
# a script that is genuinely missing, so this list and the steps below it move
# together: a name here that no step runs reddens the job for nothing, and a
# step running a script absent from it exits 127 a minute later.
EXPECTED_SCRIPTS = (
    "measure-context.sh",
    "check-seams.sh",
    "check-counts.sh",
    "record-telemetry.sh",
    "merge-token-counts.sh",
)


def _shell_var(script: str) -> str:
    """``measure-context.sh`` -> ``MEASURE_CONTEXT_SH``, as the step derives it."""
    return script.upper().replace("-", "_").replace(".", "_")


@cache
def _steps() -> tuple[tuple[str, str], ...]:
    """``(name, run-body)`` per step, in file order, bodies dedented.

    A list rather than a dict keyed by name: two steps may legitimately share a
    name, and a dict would collapse them silently - dropping one from the scan
    below, so the guard would under-report rather than fail.
    """
    text = WORKFLOW.read_text(encoding="utf-8")
    steps: list[tuple[str, str]] = []
    for match in re.finditer(r"^ *- name: (.+?)\n(.*?)(?=^ *- name: |\Z)", text, re.S | re.M):
        name, body = match.group(1).strip(), match.group(2)
        run = re.search(r"^( *)run: (\|.*?\n)?(.*?)(?=^\1[a-z_-]+:|\Z)", body, re.S | re.M)
        steps.append((name, re.sub(r"^ +", "", run.group(3), flags=re.M) if run else ""))
    return tuple(steps)


def _resolve_index() -> int:
    for index, (name, _) in enumerate(_steps()):
        if name == RESOLVE_STEP:
            return index
    raise AssertionError(f"no '{RESOLVE_STEP}' step in {WORKFLOW}")


@cache
def _resolve_script() -> str:
    return _steps()[_resolve_index()][1]


@cache
def _later_steps() -> str:
    """Every step after the resolve step, concatenated."""
    return "\n".join(body for _, body in _steps()[_resolve_index() + 1 :])


def _step_body(name: str) -> str:
    """The run body of the one step called ``name``."""
    for step_name, body in _steps():
        if step_name == name:
            return body
    raise AssertionError(f"no '{name}' step in {WORKFLOW}")


def _run_step(body: str, project: Path, **extra_env: str) -> subprocess.CompletedProcess:
    """Execute a step's shell in ``project`` with ``GITHUB_ENV`` captured."""
    env_file = project / "github_env"
    env_file.touch()
    return subprocess.run(
        ["bash", "-e", "-c", body],
        cwd=project,
        env={
            "PATH": "/usr/bin:/bin",
            "HOME": str(project),
            "GITHUB_ENV": str(env_file),
            **extra_env,
        },
        capture_output=True,
        text=True,
        timeout=60,
    )


def _run_resolve(project: Path) -> subprocess.CompletedProcess:
    """Execute the resolve step in ``project``."""
    return _run_step(_resolve_script(), project)


def _exported(project: Path) -> dict[str, str]:
    return dict(
        line.split("=", 1)
        for line in (project / "github_env").read_text().splitlines()
        if "=" in line
    )


def _run_sweep(project: Path, **extra_env: str) -> subprocess.CompletedProcess:
    """Execute the sweep step against stub check scripts.

    The step writes its scratch files to ``/tmp`` by name, which two suites
    running at once would share; the redirects are re-pointed into ``project``
    so the run is hermetic. Nothing else is rewritten - the sed extraction and
    the ``$GITHUB_ENV`` appends under test are the workflow's own text.
    """
    raw = _step_body(SWEEP_STEP)
    body = raw.replace("/tmp/", f"{project}/")
    assert body != raw, "the sweep step's scratch paths were not re-pointed"
    return _run_step(body, project, **extra_env)


def _stub(project: Path, name: str, *, prints: str, exit_code: int = 0) -> str:
    """A stand-in check script that prints ``prints`` and exits ``exit_code``."""
    path = project / name
    path.write_text(f"#!/usr/bin/env bash\ncat <<'OUT'\n{prints}\nOUT\nexit {exit_code}\n")
    path.chmod(0o755)
    return str(path)


def _fixture_project(tmp_path: Path, *, skill_scripts: tuple[str, ...], own: tuple[str, ...]):
    """A project tree: ``own`` under ``scripts/``, ``skill_scripts`` under the skill."""
    for name in own:
        (tmp_path / "scripts").mkdir(exist_ok=True)
        (tmp_path / "scripts" / name).write_text("#!/usr/bin/env bash\n")
    skill = tmp_path / ".claude" / "skills" / "curating-context" / "scripts"
    skill.mkdir(parents=True, exist_ok=True)
    for name in skill_scripts:
        (skill / name).write_text("#!/usr/bin/env bash\n")
    return tmp_path


# --- shape ---------------------------------------------------------------------


def test_no_step_joins_a_script_onto_a_shared_directory() -> None:
    """The #301 shape: one exported directory, every script hung off it."""
    assert "SKILL_SCRIPTS" not in _later_steps(), (
        "a later step joins a script name onto a shared directory variable; "
        "export one path per script instead (gregoryfoster/skills#301)"
    )


@pytest.mark.parametrize("script", EXPECTED_SCRIPTS)
def test_each_script_a_later_step_runs_is_resolved(script: str) -> None:
    """Every script the job runs is named in the resolve step's list."""
    assert script in _resolve_script(), f"{script} is run but never resolved"


def test_every_resolved_script_is_actually_run() -> None:
    """A name in the list that no step runs would fail the job for nothing."""
    for script in re.findall(r"[a-z-]+\.sh", _resolve_script()):
        assert f"${_shell_var(script)}" in _later_steps(), f"{script} is resolved but never run"


# --- behaviour, by running the step --------------------------------------------


def test_resolves_every_script_from_the_skill_directory(tmp_path: Path) -> None:
    """The ordinary case: no project copies, everything under the skill."""
    project = _fixture_project(tmp_path, skill_scripts=EXPECTED_SCRIPTS, own=())
    result = _run_resolve(project)
    assert result.returncode == 0, result.stderr
    exported = _exported(project)
    for script in EXPECTED_SCRIPTS:
        path = exported.get(_shell_var(script))
        assert path, f"{script} was not exported"
        assert (project / path).is_file(), f"{_shell_var(script)}={path} does not exist"


def test_a_lone_project_copy_does_not_redirect_the_others(tmp_path: Path) -> None:
    """#301 exactly: `scripts/` holds one script; the rest stay with the skill."""
    project = _fixture_project(
        tmp_path, skill_scripts=EXPECTED_SCRIPTS, own=("measure-context.sh",)
    )
    result = _run_resolve(project)
    assert result.returncode == 0, result.stderr
    exported = _exported(project)
    assert exported[_shell_var("measure-context.sh")] == "scripts/measure-context.sh"
    for script in EXPECTED_SCRIPTS[1:]:
        path = exported[_shell_var(script)]
        assert (project / path).is_file(), f"{script} resolved to a missing {path}"


def test_a_script_found_nowhere_fails_the_step_by_name(tmp_path: Path) -> None:
    """Better a red resolve step than a later step exiting 127."""
    project = _fixture_project(tmp_path, skill_scripts=EXPECTED_SCRIPTS[:-1], own=())
    result = _run_resolve(project)
    assert result.returncode != 0, "a missing script must stop the job here"
    assert EXPECTED_SCRIPTS[-1] in result.stderr, result.stderr


# --- the telemetry variables ---------------------------------------------------


@cache
def _swept_variables() -> tuple[str, ...]:
    """The variables the sweep step exports - read from running it.

    Not a regex over the YAML. An ``echo`` swapped for a ``printf``, or four
    appends folded into one redirected block, changes the text and not the
    behaviour; a pattern that then matches two of the four names leaves half
    the pairing below silently unguarded, which is the under-reporting
    ``_steps()`` above is written to avoid. A run cannot half-see them.
    """
    with tempfile.TemporaryDirectory() as tmp:
        project = Path(tmp)
        result = _run_sweep(
            project,
            CHECK_SEAMS_SH=_stub(project, "check-seams.sh", prints="seams: 1\nseams_acked: 2"),
            CHECK_COUNTS_SH=_stub(project, "check-counts.sh", prints="counts: 3\ncounts_acked: 4"),
        )
        assert result.returncode == 0, result.stderr
        found = tuple(_exported(project))
    assert found, f"the '{SWEEP_STEP}' step exported nothing at all"
    return found


def test_the_sweep_runs_both_checks() -> None:
    """A class swept by no script is a ledger field that is null forever."""
    body = _step_body(SWEEP_STEP)
    for script in ("check-seams.sh", "check-counts.sh"):
        assert f"${_shell_var(script)}" in body, f"{script} is never swept (archiver#249)"


@pytest.mark.parametrize("variable", ("SEAMS", "SEAMS_ACKED", "COUNTS", "COUNTS_ACKED"))
def test_each_swept_variable_reaches_record_telemetry(variable: str) -> None:
    """Measuring a number and not passing it on records `null` just the same."""
    assert variable in _swept_variables(), f"{variable} is never swept (archiver#249)"
    flag = "--" + variable.lower().replace("_", "-")
    assert f"${{{variable}:+{flag} " in _step_body(RECORD_STEP), (
        f"{variable} is swept but never handed to record-telemetry.sh as {flag}, "
        f"so its ledger field stays null (archiver#249)"
    )


def test_no_swept_variable_goes_unrecorded() -> None:
    """The pairing in the other direction: an export no later step consumes."""
    record = _step_body(RECORD_STEP)
    for variable in _swept_variables():
        assert f"${{{variable}:+" in record, f"{variable} is swept but never recorded"


def test_the_sweep_exports_every_number_it_read(tmp_path: Path) -> None:
    """Four distinct numbers, so a pattern matching the wrong line is visible."""
    result = _run_sweep(
        tmp_path,
        CHECK_SEAMS_SH=_stub(
            tmp_path, "check-seams.sh", prints="seams: 1\nseams_acked: 20", exit_code=3
        ),
        CHECK_COUNTS_SH=_stub(
            tmp_path, "check-counts.sh", prints="counts: 3\ncounts_acked: 7", exit_code=3
        ),
    )
    # Both checks exit non-zero on a finding, which is a number to record and
    # not a reason to stop measuring.
    assert result.returncode == 0, result.stderr
    assert _exported(tmp_path) == {
        "SEAMS": "1",
        "SEAMS_ACKED": "20",
        "COUNTS": "3",
        "COUNTS_ACKED": "7",
    }


def test_a_check_that_printed_no_number_exports_nothing_for_it(tmp_path: Path) -> None:
    """Empty, not zero: `${COUNTS:+...}` then drops the flag (#249).

    A check that crashed knows nothing about the surface. Exporting `0` would
    record "no unjudged counts" on the strength of a traceback; the empty
    string omits the flag and the field is honestly null.
    """
    result = _run_sweep(
        tmp_path,
        CHECK_SEAMS_SH=_stub(tmp_path, "check-seams.sh", prints="seams: 0\nseams_acked: 4"),
        CHECK_COUNTS_SH=_stub(
            tmp_path, "check-counts.sh", prints="Traceback (most recent call last):", exit_code=1
        ),
    )
    assert result.returncode == 0, result.stderr
    exported = _exported(tmp_path)
    assert exported["COUNTS"] == "", exported
    assert exported["COUNTS_ACKED"] == "", exported
    assert exported["SEAMS"] == "0", "a real zero must still be recorded as zero"
