"""The scheduled cadence workflow resolves one path per script, not one directory.

``.github/workflows/context-cadence.yml`` is generated by curating-context's
``install-cadence.sh`` and runs five of that skill's scripts. Its resolve step
used to probe a single anchor - ``measure-context.sh`` - and export the
*directory* it was found in, which every later step then joined a script name
onto. A project ``scripts/`` holding that one file sent the others to a
directory that lacks them (gregoryfoster/skills#301, fixed upstream in
``7b0ef6a`` and carried here by archiver#243).

Latent rather than live: archiver's ``scripts/`` holds ``dev_server.sh`` and
``sync_wheelhouse.py``, none of the cadence scripts. But it is a scheduled job
with a credential and a push, so its failure mode is a red Monday-morning run
nobody is watching, and the cheapest guard is to execute the step.

**Runs the workflow's own shell rather than asserting on its text.** A regex
over YAML would pass on a step that exports the right names and resolves them
wrongly. The step is extracted verbatim and run under ``bash -e`` against
fixture projects, which is what upstream's ``test_per_script_resolution.py``
does for the three copies it pins to each other.
"""

import re
import subprocess
from functools import cache
from pathlib import Path

import pytest

from tests.scripts._skills_lists import REPO_ROOT

WORKFLOW = REPO_ROOT / ".github" / "workflows" / "context-cadence.yml"
RESOLVE_STEP = "Resolve the skill scripts"

# The scripts this workflow actually runs. Upstream's list also carries
# check-counts.sh; archiver's copy has no step for it, and a resolve step is
# entitled to fail on a script that is genuinely missing, so listing one the
# job never runs would redden the run for nothing.
EXPECTED_SCRIPTS = (
    "measure-context.sh",
    "check-seams.sh",
    "record-telemetry.sh",
    "merge-token-counts.sh",
)


def _shell_var(script: str) -> str:
    """``measure-context.sh`` -> ``MEASURE_CONTEXT_SH``, as the step derives it."""
    return script.upper().replace("-", "_").replace(".", "_")


@cache
def _steps() -> tuple[tuple[str, str], ...]:
    """``(name, run-body)`` per step, in file order, bodies dedented.

    A list rather than a dict keyed by name: two steps may legitimately share a
    name, and a dict would collapse them silently - dropping one from the scan
    below, so the guard would under-report rather than fail.
    """
    text = WORKFLOW.read_text(encoding="utf-8")
    steps: list[tuple[str, str]] = []
    for match in re.finditer(r"^ *- name: (.+?)\n(.*?)(?=^ *- name: |\Z)", text, re.S | re.M):
        name, body = match.group(1).strip(), match.group(2)
        run = re.search(r"^( *)run: (\|.*?\n)?(.*?)(?=^\1[a-z_-]+:|\Z)", body, re.S | re.M)
        steps.append((name, re.sub(r"^ +", "", run.group(3), flags=re.M) if run else ""))
    return tuple(steps)


def _resolve_index() -> int:
    for index, (name, _) in enumerate(_steps()):
        if name == RESOLVE_STEP:
            return index
    raise AssertionError(f"no '{RESOLVE_STEP}' step in {WORKFLOW}")


@cache
def _resolve_script() -> str:
    return _steps()[_resolve_index()][1]


@cache
def _later_steps() -> str:
    """Every step after the resolve step, concatenated."""
    return "\n".join(body for _, body in _steps()[_resolve_index() + 1 :])


def _run_resolve(project: Path) -> subprocess.CompletedProcess:
    """Execute the resolve step in ``project`` with ``GITHUB_ENV`` captured."""
    env_file = project / "github_env"
    env_file.touch()
    return subprocess.run(
        ["bash", "-e", "-c", _resolve_script()],
        cwd=project,
        env={"PATH": "/usr/bin:/bin", "HOME": str(project), "GITHUB_ENV": str(env_file)},
        capture_output=True,
        text=True,
        timeout=60,
    )


def _exported(project: Path) -> dict[str, str]:
    return dict(
        line.split("=", 1)
        for line in (project / "github_env").read_text().splitlines()
        if "=" in line
    )


def _fixture_project(tmp_path: Path, *, skill_scripts: tuple[str, ...], own: tuple[str, ...]):
    """A project tree: ``own`` under ``scripts/``, ``skill_scripts`` under the skill."""
    for name in own:
        (tmp_path / "scripts").mkdir(exist_ok=True)
        (tmp_path / "scripts" / name).write_text("#!/usr/bin/env bash\n")
    skill = tmp_path / ".claude" / "skills" / "curating-context" / "scripts"
    skill.mkdir(parents=True, exist_ok=True)
    for name in skill_scripts:
        (skill / name).write_text("#!/usr/bin/env bash\n")
    return tmp_path


# --- shape ---------------------------------------------------------------------


def test_no_step_joins_a_script_onto_a_shared_directory() -> None:
    """The #301 shape: one exported directory, every script hung off it."""
    assert "SKILL_SCRIPTS" not in _later_steps(), (
        "a later step joins a script name onto a shared directory variable; "
        "export one path per script instead (gregoryfoster/skills#301)"
    )


@pytest.mark.parametrize("script", EXPECTED_SCRIPTS)
def test_each_script_a_later_step_runs_is_resolved(script: str) -> None:
    """Every script the job runs is named in the resolve step's list."""
    assert script in _resolve_script(), f"{script} is run but never resolved"


def test_every_resolved_script_is_actually_run() -> None:
    """A name in the list that no step runs would fail the job for nothing."""
    for script in re.findall(r"[a-z-]+\.sh", _resolve_script()):
        assert f"${_shell_var(script)}" in _later_steps(), f"{script} is resolved but never run"


# --- behaviour, by running the step --------------------------------------------


def test_resolves_every_script_from_the_skill_directory(tmp_path: Path) -> None:
    """The ordinary case: no project copies, everything under the skill."""
    project = _fixture_project(tmp_path, skill_scripts=EXPECTED_SCRIPTS, own=())
    result = _run_resolve(project)
    assert result.returncode == 0, result.stderr
    exported = _exported(project)
    for script in EXPECTED_SCRIPTS:
        path = exported.get(_shell_var(script))
        assert path, f"{script} was not exported"
        assert (project / path).is_file(), f"{_shell_var(script)}={path} does not exist"


def test_a_lone_project_copy_does_not_redirect_the_others(tmp_path: Path) -> None:
    """#301 exactly: `scripts/` holds one script; the rest stay with the skill."""
    project = _fixture_project(
        tmp_path, skill_scripts=EXPECTED_SCRIPTS, own=("measure-context.sh",)
    )
    result = _run_resolve(project)
    assert result.returncode == 0, result.stderr
    exported = _exported(project)
    assert exported[_shell_var("measure-context.sh")] == "scripts/measure-context.sh"
    for script in EXPECTED_SCRIPTS[1:]:
        path = exported[_shell_var(script)]
        assert (project / path).is_file(), f"{script} resolved to a missing {path}"


def test_a_script_found_nowhere_fails_the_step_by_name(tmp_path: Path) -> None:
    """Better a red resolve step than a later step exiting 127."""
    project = _fixture_project(tmp_path, skill_scripts=EXPECTED_SCRIPTS[:-1], own=())
    result = _run_resolve(project)
    assert result.returncode != 0, "a missing script must stop the job here"
    assert EXPECTED_SCRIPTS[-1] in result.stderr, result.stderr
